import './global.scss';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { getUserBySessionToken } from '../database/users';
import CookieBanner from './CookieBanner';
import styles from './layout.module.scss';

// import styles from './layout.module.scss';

export const metadata = {
  title: {
    default: 'findart',
    template: '%s | findart',
  },
  icons: {
    shortcut: '/favicon.ico',
  },
};
type Props = {
  children: React.ReactNode;
};

export const dynamic = 'force-dynamic';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default async function RootLayout(props: Props) {
  const cookieStore = cookies();
  const token = cookieStore.get('sessionToken');

  // 2. validate that session
  // 3. get the user profile matching the session
  const user = token && (await getUserBySessionToken(token.value));

  return (
    <html lang="en">
      <head />
      <body className={styles.body}>
        <CookieBanner />
        <header className={styles.header}>
          <img
            className={styles.logoz}
            src="images/firstpage/logo.svg "
            alt="logo "
          />

          <nav>
            <div className={styles.auth}>
              <a href="/">Home</a>
              <a href="/arts">Arts</a>
              <a href="/categorys">Categorys</a>

              {/* <Link href="/arts/paginated">paginated</Link> */}

              <div>
                {user && user.username}
                {user ? (
                  <Link href="/logout" prefetch={false}>
                    logout
                  </Link>
                ) : (
                  <>
                    <Link href="/register">register</Link>
                    <Link href="/login">login</Link>
                  </>
                )}
              </div>
            </div>
          </nav>
        </header>

        {props.children}
        <footer className={styles.footer}>
          <div className={styles.textii}>
            <p>SUPPORT</p>
            <p>COMMUNITY</p>
            <p>CONTACT</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
