// import './global.css';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { getUserBySessionToken } from '../database/users';
import CookieBanner from './CookieBanner';

export const metadata = {
  title: {
    default: 'findart',
    template: '%s | findart',
  },
  icons: {
    shortcut: '/favicon.ico',
  },
};
type Props = {
  children: React.ReactNode;
};

export const dynamic = 'force-dynamic';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default async function RootLayout(props: Props) {
  const cookieStore = cookies();
  const token = cookieStore.get('sessionToken');

  // 2. validate that session
  // 3. get the user profile matching the session
  const user = token && (await getUserBySessionToken(token.value));

  const randomNumber = Math.floor(Math.random() * 10);
  // if i have a user the person is log in
  // if i have a user the person is log out

  return (
    <html lang="en">
      <head />
      <body>
        <CookieBanner />
        <header>
          <nav>
            <div>
              <Link href="/">Home</Link>
              <Link href="/arts">Arts</Link>
              <Link href="/categorys">Categirys</Link>
              <Link href="/arts/admin">Admin</Link>
              <Link href="/arts/paginated">paginated</Link>
              <div>{randomNumber}</div>
              <div>
                {user && user.username}
                {user ? (
                  <Link href="/logout" prefetch={false}>
                    logout
                  </Link>
                ) : (
                  <>
                    <Link href="/register">register</Link>
                    <Link href="/login">login</Link>
                  </>
                )}
              </div>
            </div>
          </nav>
        </header>
        {props.children}
      </body>
    </html>
  );
}
